CREATE TABLE IF NOT EXISTS todos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
